import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { AppRoutingModule } from './/app-routing.module';
import { CoreModule } from './core/core.module';
import { NotFoundComponent } from './modules/not-found/not-found.component';
import { SharedModule } from './shared/shared.module';
import { HttpClientModule } from '@angular/common/http';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';


@NgModule({
  declarations: [AppComponent, NotFoundComponent, AutoGeneratedComponent],
  imports: [BrowserModule, AppRoutingModule, CoreModule, SharedModule, HttpClientModule],
  bootstrap: [AppComponent]
})
export class AppModule { }
